[env]
# refer: https://stackoverflow.com/questions/4377885/is-there-a-cargo-environment-variable-for-the-workspace-directory
CARGO_WORKSPACE_DIR = { value = "", relative = "" }
TS_RS_EXPORT_DIR = { value = "ui/lib/generated/protocol", relative = "" }
TS_RS_LARGE_INT = "number"
